/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
/* tslint:disable */

import '@stencil/core';




declare global {
  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}

  namespace StencilComponents {

    interface ProkaryoteLoader {
      'message': string;
    }
  }


    interface HTMLProkaryoteLoaderElement extends StencilComponents.ProkaryoteLoader, HTMLStencilElement {}

    var HTMLProkaryoteLoaderElement: {
      prototype: HTMLProkaryoteLoaderElement;
      new (): HTMLProkaryoteLoaderElement;
    };
    

  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {
    'prokaryote-loader': JSXElements.ProkaryoteLoaderAttributes;
    }
  }

  namespace JSXElements {

    export interface ProkaryoteLoaderAttributes extends HTMLAttributes {
      'message'?: string;
    }
  }

  interface HTMLElementTagNameMap {
    'prokaryote-loader': HTMLProkaryoteLoaderElement
  }

  interface ElementTagNameMap {
    'prokaryote-loader': HTMLProkaryoteLoaderElement;
  }
}
declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;