/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ProkaryoteLoader {
    'message': string;
  }
}

declare global {


  interface HTMLProkaryoteLoaderElement extends Components.ProkaryoteLoader, HTMLStencilElement {}
  var HTMLProkaryoteLoaderElement: {
    prototype: HTMLProkaryoteLoaderElement;
    new (): HTMLProkaryoteLoaderElement;
  };
  interface HTMLElementTagNameMap {
    'prokaryote-loader': HTMLProkaryoteLoaderElement;
  }
}

declare namespace LocalJSX {
  interface ProkaryoteLoader extends JSXBase.HTMLAttributes<HTMLProkaryoteLoaderElement> {
    'message'?: string;
  }

  interface IntrinsicElements {
    'prokaryote-loader': ProkaryoteLoader;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


